name: Solar System Workflow using Docker

on: 
#   workflow_dispatch:
  push:
    branches:
      - 'feature/*'

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                os: [ubuntu-latest]
                version: [20]
        runs-on: ${{matrix.os}}
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb//localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password

        container: node:${{matrix.version}}
        steps:
        - name: Checkout Repository - ${{matrix.os}}
          uses: actions/checkout@v4
    
        - name: Install Dependencies - ${{matrix.os}} - ${{matrix.version}}
          run: npm install
    
        - name: Unit Testing  
          run: npm test
          continue-on-error: true
          
        - name: Archive Test Result - ${{matrix.os}} - ${{matrix.version}}
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml

        - name:  Cache NPM dependencies - ${{matrix.os}} - ${{matrix.version}}
          uses: actions/cache@v3
          with:
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}
            path: ~/.npm

    docker:
      runs-on: ubuntu-latest
      needs: [unit-testing]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v2.2.0
          with:
            username: dareomotayo32@gmail.com
            password: ${{secrets.DOCKER_PASSWORD}}
        - name: Docker Build
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: 'docker.io/lighthings/solar-system:${{github.sha}}'


    Discord_Report:
      needs: [unit-testing]
      if: always()
      runs-on: ubuntu-latest
      steps:
        - name: Download artifact 
          uses: actions/download-artifact@v3
          with:
            name: Mocha-Test-Result

        - name: Discord Webhook Action
          uses: tsickert/discord-webhook@v5.3.0
          with:
            webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
            raw-data: test-results.xml
